---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: obi
  namespace: monitoring
  labels:
    app.kubernetes.io/name: obi
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: obi
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: obi
    spec:
      serviceAccountName: obi
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: obi
        image: otel/ebpf-instrument:main
        imagePullPolicy: IfNotPresent
        env:
        - name: OTEL_EBPF_CONFIG_PATH
          value: '/config/obi-config.yml'
        - name: OTEL_EBPF_KUBE_METADATA_ENABLE
          value: 'true'
        - name: OTEL_EBPF_KUBE_CLUSTER_NAME
          value: 'stolos-prod' # todo patch this
        - name: KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          runAsUser: 0
          readOnlyRootFilesystem: true
          capabilities:
            add:
            - BPF
            - SYS_PTRACE
            - NET_RAW
            - CHECKPOINT_RESTORE
            - DAC_READ_SEARCH
            - PERFMON
            drop:
            - ALL
        resources:
          limits:
            cpu: 100m
            memory: 768Mi
          requests:
            cpu: 50m
            memory: 512Mi
        volumeMounts:
        - mountPath: /config
          name: obi-config
        - mountPath: /var/run/obi
          name: var-run-obi
        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - name: obi-config
        configMap:
          name: obi-config
      - name: var-run-obi
        emptyDir: {}
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
