apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: projectcontour
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/Simon-Boyer/etsmtl-pfe-cloudnative.git'
    path: k8s-manifests/base/contour
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true