apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metallb
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/Simon-Boyer/etsmtl-pfe-cloudnative.git
        revision: HEAD
        files:
          - path: common.yml
  template:
    metadata:
      name: metallb
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "-30"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: metallb-system
      source:
        repoURL: https://github.com/Simon-Boyer/etsmtl-pfe-cloudnative.git
        targetRevision: HEAD
        path: k8s-manifests/base/metallb
        kustomize:
          patches:
            - target:
                group: metallb.io
                version: v1beta1
                kind: IPAddressPool
                name: public-ip
              patch: |-
                - op: replace
                  path: /spec/addresses
                  value:
                    - {{ .lb_ip }}
      ignoreDifferences:
        - group: "apiextensions.k8s.io"
          kind: CustomResourceDefinition
          name: bgppeers.metallb.io
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle
        - group: "apiextensions.k8s.io"
          kind: CustomResourceDefinition
          name: addresspools.metallb.io
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
